# ─── MULTI-LANGUAGE SUPPORT ───────────────────────────────────────────────────

TEXTS = {
    "en": {
        "welcome":        "Welcome to Nexus OlympTrade Bot!",
        "choose_lang":    "Please choose your language:",
        "lang_set":       "Language set to English!",
        "main_menu":      "Main Menu",
        "get_signal":     "Get Signal",
        "auto_signal":    "Auto Signal",
        "my_account":     "My Account",
        "settings":       "Settings",
        "status":         "Bot Status",
        "help":           "Help",
        "choose_asset":   "Choose Asset Category:",
        "choose_pair":    "Choose Asset:",
        "choose_tf":      "Choose Timeframe:",
        "choose_dur":     "Choose Trade Duration:",
        "analysing":      "Analysing market... Please wait 10-15 seconds",
        "signal_title":   "NEXUS SIGNAL",
        "direction_buy":  "BUY",
        "direction_sell": "SELL",
        "entry_price":    "Entry Price",
        "entry_time":     "Entry Time",
        "duration":       "Duration",
        "win_prob":       "Win Probability",
        "strength":       "Signal Strength",
        "indicator":      "Indicators",
        "risk":           "Trade at your own risk!",
        "auto_on":        "Auto signals ON! You will receive signals every 2 minutes.",
        "auto_off":       "Auto signals OFF!",
        "choose_mode":    "Choose signal mode:",
        "immediate":      "Immediate Signal",
        "auto_mode":      "Auto Every 2 Min",
        "back":           "Back",
        "home":           "Home",
        "new_signal":     "New Signal",
        "change_asset":   "Change Asset",
        "change_timer":   "Change Timer",
        "confirm_trade":  "Confirm Trade?",
        "yes_trade":      "YES - Trade Now",
        "no_trade":       "NO - Skip",
        "trade_placed":   "Trade placed successfully!",
        "trade_skipped":  "Trade skipped.",
        "login_olymp":    "Login to OlympTrade",
        "enter_email":    "Please enter your OlympTrade email:",
        "enter_pass":     "Please enter your OlympTrade password:",
        "login_success":  "Logged in successfully!",
        "login_fail":     "Login failed. Please try again.",
        "bot_running":    "Bot is running",
        "analyzing_24_7": "Analyzing all timeframes 24/7",
        "total_assets":   "Total Assets",
        "refresh":        "Refresh",
    },
    "sw": {
        "welcome":        "Karibu kwenye Nexus OlympTrade Bot!",
        "choose_lang":    "Tafadhali chagua lugha yako:",
        "lang_set":       "Lugha imewekwa Kiswahili!",
        "main_menu":      "Menyu Kuu",
        "get_signal":     "Pata Ishara",
        "auto_signal":    "Ishara ya Kiotomatiki",
        "my_account":     "Akaunti Yangu",
        "settings":       "Mipangilio",
        "status":         "Hali ya Bot",
        "help":           "Msaada",
        "choose_asset":   "Chagua Aina ya Mali:",
        "choose_pair":    "Chagua Mali:",
        "choose_tf":      "Chagua Muda wa Mfumo:",
        "choose_dur":     "Chagua Muda wa Biashara:",
        "analysing":      "Inachambua soko... Tafadhali subiri sekunde 10-15",
        "signal_title":   "ISHARA YA NEXUS",
        "direction_buy":  "NUNUA",
        "direction_sell": "UZA",
        "entry_price":    "Bei ya Kuingia",
        "entry_time":     "Wakati wa Kuingia",
        "duration":       "Muda",
        "win_prob":       "Uwezekano wa Kushinda",
        "strength":       "Nguvu ya Ishara",
        "indicator":      "Viashiria",
        "risk":           "Biashara kwa hatari yako mwenyewe!",
        "auto_on":        "Ishara za kiotomatiki ZIMEWASHWA!",
        "auto_off":       "Ishara za kiotomatiki ZIMEZIMWA!",
        "choose_mode":    "Chagua hali ya ishara:",
        "immediate":      "Ishara ya Haraka",
        "auto_mode":      "Kiotomatiki Kila Dakika 2",
        "back":           "Rudi",
        "home":           "Nyumbani",
        "new_signal":     "Ishara Mpya",
        "change_asset":   "Badilisha Mali",
        "change_timer":   "Badilisha Muda",
        "confirm_trade":  "Thibitisha Biashara?",
        "yes_trade":      "NDIYO - Biashara Sasa",
        "no_trade":       "HAPANA - Ruka",
        "trade_placed":   "Biashara imewekwa!",
        "trade_skipped":  "Biashara imerukwa.",
        "login_olymp":    "Ingia OlympTrade",
        "enter_email":    "Ingiza barua pepe yako ya OlympTrade:",
        "enter_pass":     "Ingiza nywila yako:",
        "login_success":  "Umeingia!",
        "login_fail":     "Imeshindwa. Jaribu tena.",
        "bot_running":    "Bot inafanya kazi",
        "analyzing_24_7": "Inachambua muda wote 24/7",
        "total_assets":   "Jumla ya Mali",
        "refresh":        "Onyesha Upya",
    },
    "fr": {
        "welcome":        "Bienvenue sur Nexus OlympTrade Bot!",
        "choose_lang":    "Veuillez choisir votre langue:",
        "lang_set":       "Langue définie en Français!",
        "main_menu":      "Menu Principal",
        "get_signal":     "Obtenir Signal",
        "auto_signal":    "Signal Auto",
        "my_account":     "Mon Compte",
        "settings":       "Paramètres",
        "status":         "Statut du Bot",
        "help":           "Aide",
        "choose_asset":   "Choisir Catégorie:",
        "choose_pair":    "Choisir Asset:",
        "choose_tf":      "Choisir Timeframe:",
        "choose_dur":     "Choisir Durée:",
        "analysing":      "Analyse du marché... Veuillez patienter 10-15 secondes",
        "signal_title":   "SIGNAL NEXUS",
        "direction_buy":  "ACHETER",
        "direction_sell": "VENDRE",
        "entry_price":    "Prix d'Entrée",
        "entry_time":     "Heure d'Entrée",
        "duration":       "Durée",
        "win_prob":       "Probabilité de Gain",
        "strength":       "Force du Signal",
        "indicator":      "Indicateurs",
        "risk":           "Tradez à vos propres risques!",
        "auto_on":        "Signaux automatiques ACTIVÉS!",
        "auto_off":       "Signaux automatiques DÉSACTIVÉS!",
        "choose_mode":    "Choisir le mode:",
        "immediate":      "Signal Immédiat",
        "auto_mode":      "Auto Toutes les 2 Min",
        "back":           "Retour",
        "home":           "Accueil",
        "new_signal":     "Nouveau Signal",
        "change_asset":   "Changer Asset",
        "change_timer":   "Changer Timer",
        "confirm_trade":  "Confirmer le Trade?",
        "yes_trade":      "OUI - Trader Maintenant",
        "no_trade":       "NON - Ignorer",
        "trade_placed":   "Trade placé avec succès!",
        "trade_skipped":  "Trade ignoré.",
        "login_olymp":    "Connexion OlympTrade",
        "enter_email":    "Entrez votre email OlympTrade:",
        "enter_pass":     "Entrez votre mot de passe:",
        "login_success":  "Connecté avec succès!",
        "login_fail":     "Échec. Veuillez réessayer.",
        "bot_running":    "Bot en cours d'exécution",
        "analyzing_24_7": "Analyse de tous les timeframes 24/7",
        "total_assets":   "Total des Assets",
        "refresh":        "Actualiser",
    },
    "ar": {
        "welcome":        "مرحباً في Nexus OlympTrade Bot!",
        "choose_lang":    "الرجاء اختيار لغتك:",
        "lang_set":       "تم تعيين اللغة إلى العربية!",
        "main_menu":      "القائمة الرئيسية",
        "get_signal":     "احصل على إشارة",
        "auto_signal":    "إشارة تلقائية",
        "my_account":     "حسابي",
        "settings":       "الإعدادات",
        "status":         "حالة البوت",
        "help":           "مساعدة",
        "choose_asset":   "اختر فئة الأصل:",
        "choose_pair":    "اختر الأصل:",
        "choose_tf":      "اختر الإطار الزمني:",
        "choose_dur":     "اختر مدة التداول:",
        "analysing":      "جارٍ تحليل السوق... انتظر 10-15 ثانية",
        "signal_title":   "إشارة NEXUS",
        "direction_buy":  "شراء",
        "direction_sell": "بيع",
        "entry_price":    "سعر الدخول",
        "entry_time":     "وقت الدخول",
        "duration":       "المدة",
        "win_prob":       "احتمالية الفوز",
        "strength":       "قوة الإشارة",
        "indicator":      "المؤشرات",
        "risk":           "تداول على مسؤوليتك الخاصة!",
        "auto_on":        "الإشارات التلقائية مفعّلة!",
        "auto_off":       "الإشارات التلقائية معطّلة!",
        "choose_mode":    "اختر وضع الإشارة:",
        "immediate":      "إشارة فورية",
        "auto_mode":      "تلقائي كل دقيقتين",
        "back":           "رجوع",
        "home":           "الرئيسية",
        "new_signal":     "إشارة جديدة",
        "change_asset":   "تغيير الأصل",
        "change_timer":   "تغيير المؤقت",
        "confirm_trade":  "تأكيد التداول؟",
        "yes_trade":      "نعم - تداول الآن",
        "no_trade":       "لا - تخطي",
        "trade_placed":   "تم التداول بنجاح!",
        "trade_skipped":  "تم تخطي التداول.",
        "login_olymp":    "تسجيل الدخول إلى OlympTrade",
        "enter_email":    "أدخل بريدك الإلكتروني:",
        "enter_pass":     "أدخل كلمة المرور:",
        "login_success":  "تم تسجيل الدخول بنجاح!",
        "login_fail":     "فشل تسجيل الدخول. حاول مجدداً.",
        "bot_running":    "البوت يعمل",
        "analyzing_24_7": "يحلل جميع الأطر الزمنية 24/7",
        "total_assets":   "إجمالي الأصول",
        "refresh":        "تحديث",
    },
    "pt": {
        "welcome":        "Bem-vindo ao Nexus OlympTrade Bot!",
        "choose_lang":    "Por favor escolha seu idioma:",
        "lang_set":       "Idioma definido para Português!",
        "main_menu":      "Menu Principal",
        "get_signal":     "Obter Sinal",
        "auto_signal":    "Sinal Automático",
        "my_account":     "Minha Conta",
        "settings":       "Configurações",
        "status":         "Status do Bot",
        "help":           "Ajuda",
        "choose_asset":   "Escolha a Categoria:",
        "choose_pair":    "Escolha o Ativo:",
        "choose_tf":      "Escolha o Timeframe:",
        "choose_dur":     "Escolha a Duração:",
        "analysing":      "Analisando mercado... Aguarde 10-15 segundos",
        "signal_title":   "SINAL NEXUS",
        "direction_buy":  "COMPRAR",
        "direction_sell": "VENDER",
        "entry_price":    "Preço de Entrada",
        "entry_time":     "Hora de Entrada",
        "duration":       "Duração",
        "win_prob":       "Probabilidade de Ganho",
        "strength":       "Força do Sinal",
        "indicator":      "Indicadores",
        "risk":           "Negocie por sua conta e risco!",
        "auto_on":        "Sinais automáticos ATIVADOS!",
        "auto_off":       "Sinais automáticos DESATIVADOS!",
        "choose_mode":    "Escolha o modo:",
        "immediate":      "Sinal Imediato",
        "auto_mode":      "Auto a cada 2 Min",
        "back":           "Voltar",
        "home":           "Início",
        "new_signal":     "Novo Sinal",
        "change_asset":   "Mudar Ativo",
        "change_timer":   "Mudar Timer",
        "confirm_trade":  "Confirmar Trade?",
        "yes_trade":      "SIM - Negociar Agora",
        "no_trade":       "NÃO - Pular",
        "trade_placed":   "Trade realizado com sucesso!",
        "trade_skipped":  "Trade ignorado.",
        "login_olymp":    "Login no OlympTrade",
        "enter_email":    "Digite seu email OlympTrade:",
        "enter_pass":     "Digite sua senha:",
        "login_success":  "Login realizado com sucesso!",
        "login_fail":     "Falha no login. Tente novamente.",
        "bot_running":    "Bot em execução",
        "analyzing_24_7": "Analisando todos os timeframes 24/7",
        "total_assets":   "Total de Ativos",
        "refresh":        "Atualizar",
    },
    "es": {
        "welcome":        "Bienvenido al Nexus OlympTrade Bot!",
        "choose_lang":    "Por favor elige tu idioma:",
        "lang_set":       "Idioma establecido en Español!",
        "main_menu":      "Menú Principal",
        "get_signal":     "Obtener Señal",
        "auto_signal":    "Señal Automática",
        "my_account":     "Mi Cuenta",
        "settings":       "Configuración",
        "status":         "Estado del Bot",
        "help":           "Ayuda",
        "choose_asset":   "Elegir Categoría:",
        "choose_pair":    "Elegir Activo:",
        "choose_tf":      "Elegir Temporalidad:",
        "choose_dur":     "Elegir Duración:",
        "analysing":      "Analizando mercado... Espera 10-15 segundos",
        "signal_title":   "SEÑAL NEXUS",
        "direction_buy":  "COMPRAR",
        "direction_sell": "VENDER",
        "entry_price":    "Precio de Entrada",
        "entry_time":     "Hora de Entrada",
        "duration":       "Duración",
        "win_prob":       "Probabilidad de Ganar",
        "strength":       "Fuerza de la Señal",
        "indicator":      "Indicadores",
        "risk":           "Opera bajo tu propio riesgo!",
        "auto_on":        "Señales automáticas ACTIVADAS!",
        "auto_off":       "Señales automáticas DESACTIVADAS!",
        "choose_mode":    "Elige el modo:",
        "immediate":      "Señal Inmediata",
        "auto_mode":      "Auto cada 2 Min",
        "back":           "Atrás",
        "home":           "Inicio",
        "new_signal":     "Nueva Señal",
        "change_asset":   "Cambiar Activo",
        "change_timer":   "Cambiar Timer",
        "confirm_trade":  "Confirmar Operación?",
        "yes_trade":      "SÍ - Operar Ahora",
        "no_trade":       "NO - Saltar",
        "trade_placed":   "Operación realizada con éxito!",
        "trade_skipped":  "Operación omitida.",
        "login_olymp":    "Iniciar sesión en OlympTrade",
        "enter_email":    "Ingresa tu email de OlympTrade:",
        "enter_pass":     "Ingresa tu contraseña:",
        "login_success":  "Sesión iniciada con éxito!",
        "login_fail":     "Error al iniciar sesión. Inténtalo de nuevo.",
        "bot_running":    "Bot en ejecución",
        "analyzing_24_7": "Analizando todos los timeframes 24/7",
        "total_assets":   "Total de Activos",
        "refresh":        "Actualizar",
    },
}

def t(lang: str, key: str) -> str:
    return TEXTS.get(lang, TEXTS["en"]).get(key, TEXTS["en"].get(key, key))
